version: '3.4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5431:5432'
    expose:
      - '5432'
    networks:
    - backed-test

  todo_app:
    build: 
      context: .
    depends_on:
      - postgres
    environment: 
      APP_NAME: TODO
      VERSION: 1.0.0
      PORT: 5000
      HOST: 0.0.0.0
      DB_USERNAME: postgres
      DB_PASSWORD: 12345678
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: be_db
      DB_DIALECT: postgres
      ACCESS_TOKEN_KEY: d0aa9c33de488cfc8ed3f9fce5c3b264bf965279d023ee10a9d93b5369c9ecd4cd5ed2cb89fd7cae380e4f8c16ff32d0a2e96b925414ee8cb03e01281710413f
      ACCESS_TOKEN_AGE: 1h
    ports:
      - '5000:5000'
    expose:
      - '5000'
    networks:
    - backed-test
    

networks:
  backed-test:
    driver: bridge